export const GET_GAME_MODES_START = 'GET_GAME_MODES_START';
export const GET_GAME_MODES_SUCCESS = 'GET_GAME_MODES_SUCCESS';
export const GET_GAME_MODES_ERROR = 'GET_GAME_MODES_ERROR';

export const SET_USER_NAME = 'SET_USER_NAME';
