export const GET_GAME_MODES_START = 'GET_GAME_MODES_START';
export const GET_GAME_MODES_SUCCESS = 'GET_GAME_MODES_SUCCESS';
export const GET_GAME_MODES_ERROR = 'GET_GAME_MODES_ERROR';

export const GET_LEADERS_START = 'GET_LEADERS_START';
export const GET_LEADERS_SUCCESS = 'GET_LEADERS_SUCCESS';
export const GET_LEADERS_ERROR = 'GET_LEADERS_ERROR';

export const SET_USER_NAME = 'SET_USER_NAME';

export const ON_GAME_MODE_SELECT = 'ON_GAME_MODE_SELECT';
